<!DOCTYPE html>
<html lang="en" class="no-js">

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Kotti Demo -- failed to build</title>

    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css">
  </head>

  <body class="bg-red-50 antialiased max-w-4xl mx-auto p-4 my-2">
    <h1 class="text-red-700 text-5xl text-center">
      Build Failed!
    </h1>
    <div class="mt-2">
      <div class="text-gray-700 text-center font-semibold">21 Jul 2025 01:24:31 UTC</div>
    </div>
    <div class="mt-4">
      <div class="text-red-700 bg-red-100 border border-red-200 p-4 rounded text-center font-semibold">
        Unless all site previews are broken, this is a problem with the
        <a class="underline"
          href="https://pypi.org/project/kotti-docs-theme/"><code>kotti-docs-theme</code></a>
        package.
      </div>
    </div>
    <div class="mt-4">
      <div class="text-gray-700 text-center font-semibold">Configuration</div>
      <pre class="bg-gray-50 border my-2 shadow rounded p-2 overflow-auto">{&#39;html_theme&#39;: &#39;kotti_docs_theme&#39;, &#39;html_theme_path&#39;: &#39;[kotti_docs_theme.get_theme_dir()]&#39;}</pre>
    </div>
    <div class="mt-4">
      <div class="text-gray-700 text-center font-semibold">Output</div>
      <pre class="bg-gray-50 border my-2 shadow rounded p-2 overflow-auto">======================================== stdout ========================================
Running Sphinx v5.0.0
making output directory... done
locale_dir /home/runner/work/sphinx-themes.org/sphinx-themes.org/sample-docs/locales/en/LC_MESSAGES does not exists
loading intersphinx inventory from https://www.sphinx-doc.org/objects.inv...
intersphinx inventory has moved: https://www.sphinx-doc.org/objects.inv -&gt; https://www.sphinx-doc.org/en/master/objects.inv
locale_dir /home/runner/work/sphinx-themes.org/sphinx-themes.org/sample-docs/locales/en/LC_MESSAGES does not exists
building [mo]: targets for 0 po files that are out of date
building [dirhtml]: targets for 18 source files that are out of date
updating environment: locale_dir /home/runner/work/sphinx-themes.org/sphinx-themes.org/sample-docs/locales/en/LC_MESSAGES does not exists
[new config] 18 added, 0 changed, 0 removed
reading sources... [  5%] index
reading sources... [ 11%] kitchen-sink/admonitions
reading sources... [ 16%] kitchen-sink/api
reading sources... [ 22%] kitchen-sink/blocks
reading sources... [ 27%] kitchen-sink/generic
reading sources... [ 33%] kitchen-sink/images
reading sources... [ 38%] kitchen-sink/index
reading sources... [ 44%] kitchen-sink/lists
reading sources... [ 50%] kitchen-sink/really-long
reading sources... [ 55%] kitchen-sink/structure
reading sources... [ 61%] kitchen-sink/tables
reading sources... [ 66%] kitchen-sink/typography
reading sources... [ 72%] long-page
reading sources... [ 77%] placeholder-four
reading sources... [ 83%] placeholder-one
reading sources... [ 88%] placeholder-three
reading sources... [ 94%] placeholder-two
reading sources... [100%] really-long-title

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  5%] index
writing output... [ 11%] kitchen-sink/admonitions

======================================== stderr ========================================
/home/runner/work/sphinx-themes.org/sphinx-themes.org/sample-docs/kitchen-sink/admonitions.rst:161: ERROR: Unknown directive type &#34;versionremoved&#34;.

.. versionremoved:: v0.1.1

   Here&#39;s a version removed message.

   We also support *italic*, **bold**, ``code``, `links &lt;https://www.sphinx-doc.org/en/master/&gt;`_, and more.
/usr/lib/python3.12/urllib/parse.py:docstring of urllib.parse.quote:13: ERROR: Unexpected indentation.
/home/runner/work/sphinx-themes.org/sphinx-themes.org/sample-docs/kitchen-sink/blocks.rst:138: WARNING: Include file &#39;/home/runner/work/sphinx-themes.org/src/furo/__init__.py&#39; not found or reading it failed
/home/runner/work/sphinx-themes.org/sphinx-themes.org/sample-docs/kitchen-sink/lists.rst:202: WARNING: Include file &#39;/home/runner/work/sphinx-themes.org/src/furo/__init__.py&#39; not found or reading it failed

Traceback (most recent call last):
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/builders/html/__init__.py&#34;, line 1072, in handle_page
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/jinja2glue.py&#34;, line 189, in render
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/jinja2/environment.py&#34;, line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/jinja2/environment.py&#34;, line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/jinja2/loaders.py&#34;, line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/jinja2glue.py&#34;, line 210, in get_source
jinja2.exceptions.TemplateNotFound: page.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/cmd/build.py&#34;, line 276, in build_main
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/application.py&#34;, line 329, in build
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/builders/__init__.py&#34;, line 288, in build_update
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/builders/__init__.py&#34;, line 352, in build
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/builders/__init__.py&#34;, line 544, in write
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/builders/__init__.py&#34;, line 554, in _write_serial
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/builders/html/__init__.py&#34;, line 648, in write_doc
  File &#34;/home/runner/work/sphinx-themes.org/sphinx-themes.org/.nox/publish/lib/python3.12/site-packages/sphinx/builders/html/__init__.py&#34;, line 1079, in handle_page
sphinx.errors.ThemeError: An error happened in rendering the page kitchen-sink/admonitions.
Reason: TemplateNotFound(&#39;page.html&#39;)

Theme error:
An error happened in rendering the page kitchen-sink/admonitions.
Reason: TemplateNotFound(&#39;page.html&#39;)
</pre>
    </div>
  </body>

</html>